config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root to: 'home#index'
  get '/posts' => 'posts#show'
  get 'posts/new' => 'posts#new'
  get '/followees' => 'follows#show'
  get '/allusers' => 'users#index'
  post '/users/:id/follow', to: 'users#follow', as: 'follow_user'
  post '/users/:id/unfollow', to: 'users#unfollow', as: 'unfollow_user'
  resources :comments, only: [:create]
  resources :users, only: %i[show edit update] do
    resources :follows
  end
  resources :posts, only: %i[new create show] do
    resources :likes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_presence_of :comment
  validates_presence_of :user_id
  validates_presence_of :post_id
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'

  validates :follower_id, uniqueness: { scope: :followee_id }
  validates :followee_id, uniqueness: { scope: :follower_id }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes

  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followees, through: :followed_users
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users

  validates :username, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username first_name last_name email])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id if user_signed_in?
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_to current_user, flash: { success: 'Comment was not created' }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :post_id)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = Post.where(user_id: current_user.followees.pluck(:id)).order(created_at: :desc)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @post.likes.create(user_id: current_user.id)
    end
    redirect_to post_path(@post)
  end

  def destroy
    if !already_liked?
      flash[:notice] = 'Cannot unlike'
    else
      @like.destroy
    end
    redirect_to post_path(@post)
  end

  def find_like
    @like = @post.likes.find(params[:id])
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, post_id:
    params[:post_id]).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to current_user, flash: { success: 'Post was created' }
    else

      render :new, flash: { alert: "Post cannot be created" }
    end
  end

  private

  def post_params
    params.require(:post).permit(:image, :image_cache, :description, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user  = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    current_user.update(user_params)
    redirect_to current_user
  end

  def follow
    @user = User.find(params[:id])
    current_user.followees << @user
    redirect_back(fallback_location: user_path(@user))
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.followed_users.find_by(followee_id: @user.id).destroy
    redirect_back(fallback_location: user_path(@user))
  end

  private

  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def can_edit_profile?(profile_id)
    user_signed_in? && current_user.id == profile_id
  end
end

app/views/follows/index.html.erb
<% @user.followers.each do |f| %>
  <p> <%= f.username %> </p>
<% end %>

app/views/follows/show.html.erb
<% @user.followees.each do |f| %>

  <p> <%= f.username %> </p>
<% end %>

app/views/home/index.html.erb
<div class="posts">
  <% @posts.each do |post| %>
  <% if post.image_url %>
  <section class="post">
    <div class="user">
      <div class="avatar">
      <%= image_tag post.user.image.url if post.user.image.url %>
      </div>

      <div class="username">
      <%= link_to post.user.username, user_path(post.user_id)%>
      </div>

    </div>
    <%=link_to post_path(post) do %>
 <%= image_tag post.image_url, class: 'main-image' %>
   <% end %>


    <div class="post-actions">
      <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    </div>

    <div class="description">
      <%= link_to post.user.username, user_path(post.user_id)%>
      <%= post.description %>

    </div>
<div class ="comment">
  <h3>Comments:</h3>
    <% post.comments.each do |comment|%>
  <p>  <strong><%= comment.user.username  %></strong>
    <%= comment.comment %></p>
    <% end %>

        <div class="comment-box">
          <%= form_for Comment.new, html: { multipart: true } do |f|%>

          <%= f.hidden_field :post_id, value: post.id %>

          <div class="input-group">
            <%= f.text_field :comment, placeholder: "Add comment...", class: "form-control post-comment"%>
            <div class ="input_group-append">
              <%= f.submit "Add", class: "btn btn-success float-right" %>
              <% end %>
              </div>
              </div>
              </div>
</div>


  </section>
  <% end %>
  <% end %>
</div>

app/views/home/show.html.erb
<div class="posts">
  <% @posts.each do |post| %>
  <% if post.image_url %>
  <section class="post">
    <div class="user">
      <div class="avatar">
      <%= image_tag post.user.image.url if post.user.image.url %>
      </div>

      <div class="username">
      <%= link_to post.user.username, user_path(post.user_id)%>
      </div>

    </div>
    <%=link_to post_path(post) do %>
    <%= image_tag post.image_url, class: 'main-image' %>
    <% end %>

    <div class="post-actions">
      <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    </div>

    <div class="description">
      <%= link_to post.user.username, user_path(post.user_id)%>
      <%= post.description %>
    </div>

  <div class ="comment">
      <h3>Comments:</h3>
      <% post.comments.each do |comment|%>
      <p><strong><%= comment.user.username %></strong>
      <%= comment.comment %></p>
      <p class="text-muted"><%= time_ago_in_words comment.created_at %> ago</p>
      <% end %>

      <div class="comment-box">
      <%= form_for Comment.new, html: { multipart: true } do |f|%>
      <%= f.hidden_field :post_id, value: post.id %>
      <div class="input-group">
      <%= f.text_field :comment, placeholder: "Add comment...", class: "form-control post-comment"%>
      <div class ="input_group-append">
      <%= f.submit "Add", class: "btn btn-success float-right" %>
      <% end %>
      </div>
      </div>
      </div>
  </div>

  </section>
  <% end %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="<%= root_path %>">
            <%= fa_stacked_icon "camera inverse", base: "circle"%>
            Instagram
          </a>
        </div>

        <div class="user-section">
          <a href="<%= allusers_path %>"><i class="fa fa-users"></i></a>


          <% if user_signed_in? %>

          <a href="<%= new_post_path %>">
            <i class="fa fa-plus"> New post</i>
          </a>

          <a href="<%= user_path(current_user) %>">
            <i class="fa fa-user"></i>
          </a>
          <a href="<%= destroy_user_session_path%>" data-method="delete">
            <i class="fa fa-sign-out"></i>
          </a>
          <% else %>
          <a href="<%= new_user_session_path%>">
            <i class="fa fa-sign-in"></i>
          </a>
          <% end %>

        </div>
      </div>
    </nav>

    <!--Main content-->
    <main class="container" style="min-height: 500px;">
      <%= yield %>
    </main>

    <!--Footer-->
    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>ABOUT US
          </li>
          <li>SUPPORT</li>

        </ul>
        <p> © 2020 INSTAGRAM </p>
      </nav>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>

    <div class="form-group">
    <%= f.text_field :description %>
    </div>
    <div class="form-group">
    <%= f.file_field :image %>
    </div>
    <div class="form-group">
    <%= f.hidden_field :image_cache %>
    </div>
    <div class="form-group">
        <%= f.text_field :user_id, value: current_user.id, class:'d-none'%>
      </div>
    <br>

    <div class="text-center">
    <%= f.submit 'Create Post', class: 'btn btn-primary' %>
    </div>

<% end %>



<% if @post.errors.any? %>
<div id="error_explanation">
  <h2><% pluralize(@post.errors.count, "Error") %>
  </h2>
  <ul>
    <% @post.errors.full_messages.each do |message| %>
  <li>  <%= message %> </li>
  <% end %>
</ul>
</div>
<% end %>

app/views/posts/new.html.erb
<h2>New Post<h2/>
  <%= render "form" %>

app/views/posts/show.html.erb
<div class="posts">
  <section class="post">
    <div class="user">
      <div class="avatar">
      <%= image_tag @post.user.image.url if @post.user.image.url %>
      </div>

      <div class="username">
      <%= link_to @post.user.username, user_path(@post.user_id)%>
      </div>

    </div>

    <%= image_tag @post.image_url, class: 'main-image' %>
    <p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>

    <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
    <% if pre_like %>
      <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
    <% else %>
      <%= button_to 'Like', post_likes_path(@post), method: :post %>
    <% end %>


   <div class="description">
     <%= link_to @post.user.username, user_path(@post.user_id)%>
    <p><%= @post.description %>
    </p></div>

    <div class ="comment">
    <h3>Comments:</h3>
    <% @post.comments.each do |comment|%>
    <p>  <strong><%= comment.user.username  %></strong>
    <%= comment.comment %></p>
    <% end %>

        <div class="comment-box">
          <%= form_for Comment.new, html: { multipart: true } do |f|%>

          <%= f.hidden_field :post_id, value: @post.id %>

          <div class="input-group">
            <%= f.text_field :comment, placeholder: "Add comment...", class: "form-control post-comment"%>
            <div class ="input_group-append">
              <%= f.submit "Add", class: "btn btn-success float-right" %>
              <% end %>
              </div>
        </div>
    </div>
</div>
  </section>
</div>

app/views/users/edit.html.erb
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true">Edit Profile</a>


    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">

      <%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
        <div class="form-group row">
          <div class="col-sm-3 col-form-label">
            <img class="avatar" <% if @user.image_url %> <%= image_tag @user.image_url  %>
              <% else %>
               <img class="avatar" src="#"> 
                <% end %>
          </div>
          <div class="col-sm-9">
            <p class="username"><%=current_user.username %></p>
            <%= f.label :image %>
            <%= f.file_field :image %>
            <%= f.hidden_field :image_cache %>

          </div>
        </div>
        <div class="form-group row">
          <%= f.label :first_name, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :first_name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :username, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :username, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :last_name, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :last_name, class: 'form-control' %>
          </div>
        </div>

              <div class="form-group row">
          <%= f.label :email, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :email, class: 'form-control' %>
          </div>
        </div>


        <div class="form-group row">
          <div class="col-sm-3">
          </div>
          <div class="col-sm-9">
            <%= f.submit "Submit", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>


    </div>
  </div>
</div>

app/views/users/index.html.erb
All users:
<% @users.each do |f| %>
<p><%= link_to f.username, user_path(f) %></p>
<% end %>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
          <% if @user.image_url %>
        <%= image_tag @user.image_url  %>
        <% end %>
      </div>
    </div>

    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= @user.username %></h2>
        <div class = "text-center">
        <%= link_to "Edit profile",  edit_user_path(current_user), class: "btn btn-secondary btn-sm"  if can_edit_profile?(@user.id) %>
        </div>

      </div>
      <ul class="posts">
        <li><span><%= @user.posts.count %></span> posts</li>
        <li><span><%= @user.followers.count %></span> <%= link_to 'Followers', user_follows_path(@user) %></li>
        <li><span><%= @user.followees.count %></span> <%= link_to 'Following', user_follow_path(@user) %></li>
        <h2 class="name"><%= @user.first_name + " " + @user.last_name %></h2>
      </ul>



      <section id="all-links">
          <% if @user.id == current_user.id %>
              <%= link_to "MyPage", current_user %>
          <% elsif current_user.followees.include?(@user) %>
              <h5><%= button_to "Unfollow", unfollow_user_path, method: "POST" %></h5>
          <% else %>
              <h5><%= button_to "Follow", follow_user_path, method: "POST"  %></h5>
          <% end%>


          <br>


      </section>




    </div>

  </div>

<div class="user-tabs">
  <a class="tab active" href=""><i class="fa fa-th"></i>POSTS</a>
</div>


<div class="user-images">
  <% @posts.each do |post|%>
    <% if post.image_url %>
    <div class="wrapper">
       <%=link_to post_path(post) do %>
    <%= image_tag post.image_url %>
      <% end %>
    </div>
  <% end %>
  <% end %>
</div>
</div>